services:
  backend:
    platform: linux/amd64
    image: umasscds/bb_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    restart: always
  
  frontend:
    platform: linux/amd64
    image: umasscds/bb_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
